#!/bin/sh

LOADDIR="/etc/hinit/[LOAD]/onshut"


if [ ! -d "$LOADDIR" ]; then
    exit 0
fi


for service in "$LOADDIR"/*
do
    if [ -L "$service" ]; then

        SERVICE_PATH=$(readlink -f "$service")

        if [ -x "$SERVICE_PATH/stop" ]; then
            "$SERVICE_PATH/stop"
        fi

    fi
done


exit 0
