#!/bin/sh

LOADDIR="/etc/hinit/[LOAD]/onboot"

if [ ! -d "$LOADDIR" ]; then
    exit 0
fi


for service in "$LOADDIR"/*
do
    if [ -L "$service" ]; then

        SERVICE_PATH=$(readlink -f "$service")

        if [ -x "$SERVICE_PATH/run" ]; then
            "$SERVICE_PATH/run" &
        fi

    fi
done


exit 0
